### ISSUE TITLE
error frontend

### ISSUE THREAD

**Issue by VictorCinetic** [mage2pro/square#33]
Hi we are trying your module in a magento 2.3 to see if we can use it  but in the checkout we can't write any credit card
![imagen](https://user-images.githubusercontent.com/46021330/80697512-5792db80-8ad9-11ea-9706-9f21adf6a05d.png)

can you help us?

**Comment by dmitrii-fediuk** [comment]
Hire me in Upwork: [upwork.com/fl/mage2pro](https://www.upwork.com/fl/mage2pro)
